name: Deploy Production

on:
  push:
    branches: 
      - main
    tags-ignore:
      - '**'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'MinecraftTAS/minecrafttas.com'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
    
      - name: Build
        run: hugo

      - name: Deploy with Rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude .htaccess --exclude shields/
          path: public/
          remote_path: ${{ secrets.SERVER_DEPLOY_PATH }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER_NAME }}
          remote_key: ${{ secrets.SERVER_USER_KEY }}
